
package com.mycompany.projetointegrador;

public class Quest {
        public static String[][] Quest() {
            
            String[][] questoes = {
                { "Qual o nome do cantor e dançarino Naldo?",
                        "A) Arnaldo",
                        "B) Ronaldo",
                        "C) Reinaldo",
                        "D) Naldo",
                        "2",
                        "0" },

                { "No seriado 'El Chavo del Ocho', mais conhecido como Chaves aqui no Brasil, a personagem 'Dona Clotilde' foi apelidada pelas crianças como a 'Bruxa do ...'",
                        "A) 71",
                        "B) 91",
                        "C) 51",
                        "D) 361",
                        "1",
                        "0" },

                { "Qual o nome do Super Choque?",
                        "A) Vurgil Hawkins",
                        "B) Vurgil Hawkins Ovid",
                        "C) Willian Hawkins",
                        "D) Virgil Ovid Hawkins",
                        "4",
                        "0" },

                { "O que a palavra legend significa em português?",
                        "A) Legenda",
                        "B) Conto",
                        "C) Lenda",
                        "D) Legendário",
                        "3",
                        "0" },

                { "Qual o número mínimo de jogadores em cada time numa partida de futebol?",
                        "A) 8",
                        "B) 10",
                        "C) 9",
                        "D) 7",
                        "4",
                        "0" },

                { "Quais as duas datas que são comemoradas em novembro?",
                        "A) Independência do Brasil e Dia da Bandeira",
                        "B) Proclamação da República e Dia Nacional da Consciência Negra",
                        "C) Black Friday e Dia da Árvore",
                        "D) Dia de Finados e Dia Nacional do Livro",
                        "2",
                        "0" },

                { "Quanto tempo a luz do Sol demora para chegar à Terra?",
                        "A) 12 minutos",
                        "B) 1 dia",
                        "C) 12 horas",
                        "D) 8 minutos",
                        "4",
                        "0" },

                { "Que animal gruguleja?",
                        "A) o pavão",
                        "B) a garça",
                        "C) o peru",
                        "D) a cacatua",
                        "3",
                        "0" },

                { "Qual destas obras arquitetônicas brasileiras é uma das Sete Maravilhas do Mundo Moderno?",
                        "A) Elevador Lacerda",
                        "B) Cristo Redentor",
                        "C) Estação da Luz",
                        "D) One Tower",
                        "2",
                        "0" },

                { "O que é Pix?",
                        "A) Meio de pagamento instantâneo criado pelo Banco Central do Brasil",
                        "B) Plano de investimento de baixo risco do Banco do Brasil",
                        "C) Conjunto de formas de pagamento realizados por subadquirentes",
                        "D) Forma de pagamento online",
                        "1",
                        "0" },

                { "Qual a montanha mais alta do mundo?",
                        "A) Mauna Kea",
                        "B) Dhaulagiri",
                        "C) Monte Chimborazo",
                        "D) Monte Everest",
                        "4",
                        "0" },

                { "Quanto tempo a Terra demora para dar uma volta completa em torno dela mesma?",
                        "A) Aproximadamente 24 horas",
                        "B) 365 dias",
                        "C) 7 dias",
                        "D) 30 ou 31 dias",
                        "1",
                        "0" },

                { "Qual a maior floresta tropical do mundo?",
                        "A) Mata Atlântica",
                        "B) Pampas",
                        "C) Pantanal",
                        "D) Floresta Amazônica",
                        "4",
                        "0" },

                { "Kryptonita é a fraqueza de qual super-herói?",
                        "A) Batman",
                        "B) Hulk",
                        "C) Super-Homem",
                        "D) Capitão América",
                        "3",
                        "0" },

                { "Qual a personagem mais famosa de Maurício de Sousa?",
                        "A) Mafalda",
                        "B) Mônica",
                        "C) Smurfette",
                        "D) Magali",
                        "2",
                        "0" },

                { "Que cidade brasileira é conhecida por chover todos os dias quase à mesma hora?",
                        "A) São Paulo",
                        "B) Joinville",
                        "C) Belém",
                        "D) Natal",
                        "3",
                        "0" },

                { "Qual o maior podcast do Brasil?",
                        "A)Podpah",
                        "B)PODPAH",
                        "C)Podpah é muito zika assista",
                        "D)PODPAH",
                        "3",
                        "0" },

                { "Em que país foi construído o Muro de Berlim?",
                        "A) Estados Unidos",
                        "B) China",
                        "C) Brasil",
                        "D) Alemanha",
                        "4",
                        "0" },

                { "Depois do futebol, qual o esporte mais popular no Brasil?",
                        "A) Esqui",
                        "B) Vôlei",
                        "C) Hóquei no gelo",
                        "D) Golfe",
                        "2",
                        "0" },

                { "Em que conto de fadas uma princesa adormece com um feitiço e só acorda com o beijo de um príncipe?",
                        "A)A Bela Adormecida",
                        "B)João e Maria",
                        "C)Chapeuzinho Vermelho",
                        "D)Patinho Feio",
                        "1",
                        "0" },

                { "Que fruto nasce da oliveira?",
                        "A)Amêndoa",
                        "B)Abacate",
                        "C)Azeitona",
                        "D)Açaí",
                        "3",
                        "0" },

                { "Qual o plural de chapéu?",
                        "A) Chapéis",
                        "B) Chapéus",
                        "C) Chapéuzes",
                        "D) Chapuzes",
                        "2",
                        "0" },

                { "Que navio famoso naufragou na sua viagem inaugural?",
                        "A) Titanic",
                        "B) Antonov",
                        "C) Boeing",
                        "D) Airbus",
                        "1",
                        "0" },
                { "Qual a altura da rede de vôlei nos jogos masculino e feminino?", 
                        "A)2,4 para ambos",
                        "B)2,5 m e 2,0 m",
                        "C)1,8 m e 1,5 m",
                        "D)2,43 m e 2,24 m",
                        "4",
                        "0" },

                { "Qual personagem folclórico costuma ser agradado pelos caçadores com a oferta de fumo?", 
                        "A)Caipora",
                        "B)Saci",
                        "C)Lobisomem",
                        "D)Boitatá",
                        "1",
                        "0" },

                { "Qual a montanha mais alta do Brasil?", 
                        "A)Pico da Neblina",
                        "B)Pico Paraná",
                        "C)Monte Roraima",
                        "D)Pico Maior de Friburgo",
                        "1",
                        "0" },

                { "Quais destas doenças são sexualmente transmissíveis?", 
                        "A)Aids, tricomoníase e ebola",
                        "B)Chikungunya, aids e herpes genital",
                        "C)Gonorreia, clamídia e sífilis",
                        "D)Botulismo, cistite e gonorreia",
                        "3",
                        "0" },


                { "Qual o maior animal terrestre?", 
                        "A)Baleia Azul",
                        "B)Dinossauro",
                        "C)Elefante africano",
                        "D)Girafa",
                        "3",
                        "0" },

                { "Com que dois países faz fronteira o Equador?", 
                        "A)com o Brasil e com a Colômbia",
                        "B)com a Colômbia e com a Venezuela",
                        "C)com a Colômbia e com o Peru",
                        "D)com o Equador e o Brasil",
                        "3",
                        "0" },

                { "Qual das alternativas contém apenas vacinas contra a covid-19?", 
                        "A)VIP/VOP e AstraZeneca",
                        "B)CoronaVac e AstraZeneca",
                        "C)HPV e BioNTech",
                        "D)Pentavalente (DTPa) e Sputnik V",
                        "2",
                        "0" },

                { "Qual das alternativas traz uma das medidas do presidente Trump, anunciada em 2017, que causou polêmica?", 
                        "A)Construção de um muro na fronteira com o Canadá",
                        "B)Cessação de Acordo de Comércio Livre (ACL) entre os Estados Unidos e Israel",
                        "C)Saída do Acordo de Paris",
                        "D)Saída da OTAN - Organização do Tratado do Atlântico Norte",
                        "3",
                        "0" },

                { "O que é Pix?", 
                        "A)Meio de pagamento instantâneo criado pelo Banco Central do Brasil",
                        "B)respPlano de investimento de baixo risco do Banco do Brasil",
                        "C)Conjunto de formas de pagamento realizados por subadquirentes",
                        "D)Forma de pagamento online",
                        "1",
                        "0" },

                { "Qual a função da ONU?", 
                        "A)Zelar pela cultura em todas as nações",
                        "B)Unir as nações com o objetivo de manter a paz e a segurança mundial",
                        "C)Financiar países em desenvolvimento",
                        "D)Regular o funcionamento do sistema financeiro a nível internacional",
                        "2",
                        "0" },
            };  
            
            return questoes;
        }
        
        public static void main(String[] args){
            
        }
}




